### ISSUE TITLE
System.TypeLoadException: Could not load type "Microsoft.CodeQuality.CSharp.Analyzers.ApiDesignGuidelines.CSharpEnumsShouldHavePluralNamesFixer" from assembly "Microsoft.CodeQuality.CSharp.Analyzers, Version=3.0.0.0"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn-analyzers#3770]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1084977/systemtypeloadexception-could-not-load-type-micros.html)._

---
[regression] [worked-in:16.5]
Every time start working in a solution, I get this exception or also other analyzer loading exceptions after a short time.

We use in generall the following analyzers in our solutions 

```
  <ItemGroup Label="Code Analysis">
    <PackageReference Include="Lindhart.Analyser.MissingAwaitWarning" Version="1.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="AsyncFixer" Version="1.3.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" Version="3.6.0" Condition=" !$(MSBuildProjectName.ToLower().EndsWith('tests')) ">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.6.0" Condition=" !$(MSBuildProjectName.ToLower().EndsWith('tests')) ">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="3.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.Razor" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <!--<PackageReference Include="CSharpGuidelinesAnalyzer" Version="3.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>-->
  </ItemGroup>
```

---
#### Visual Studio Feedback System on 6/19/2020, 00:37 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 6/22/2020, 09:53 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
I believe this should be fixed in latest 3.3.x packages. Can you try one from https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet5&package=Microsoft.CodeAnalysis.FxCopAnalyzers&protocolType=NuGet&version=3.3.0-beta1.20322.2&view=versions? We hope to release a 3.3.0-beta1 soon.

**Comment by knoxi** [comment]
I used the latest packages of `Microsoft.CodeAnalysis.CSharp.Features (3.7.0-3.20271.4)`, `Microsoft.CodeAnalysis.CSharp (3.7.0-3.20271.4)`, `Microsoft.CodeAnalysis.FxCopAnalyzers (3.3.0-beta1.20323.3)` from your provided feed but still get the type load exception.

```
  <entry>
    <record>3303</record>
    <time>2020/06/24 11:55:22.388</time>
    <type>Error</type>
    <source>Microsoft.VisualStudio.ComponentModelHost.VsShellComponentModelHost</source>
    <description>An invalid MEF cache has been found due to a mismatching timestamp or MVID: Microsoft.VisualStudio.ExtensibilityHosting.InvalidMEFCacheException: The Visual Studio component cache is out of date (assembly: Microsoft.CodeQuality.CSharp.Analyzers, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35). Please restart Visual Studio.;VS.Platform.ExtensibilityHosting.MefCacheInvalidation.LoadedAssembly.Name=Microsoft.CodeQuality.CSharp.Analyzers, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35;VS.Platform.ExtensibilityHosting.MefCacheInvalidation.LoadedAssembly.CodeBase=file:///C:/Users/DemianMarty/AppData/Local/Temp/VS/AnalyzerAssemblyLoader/0e2dfb74415b420ea59977303c81d2b9/2/Microsoft.CodeQuality.CSharp.Analyzers.dll;VS.Platform.ExtensibilityHosting.MefCacheInvalidation.ActualTimestamp=637236100520000000;VS.Platform.ExtensibilityHosting.MefCacheInvalidation.ExpectedTimestamp=636933548801591542;VS.Platform.ExtensibilityHosting.MefCacheInvalidation.ActualMVID=a8fb44ad-bcbd-481f-beac-ff3b52b295b4;VS.Platform.ExtensibilityHosting.MefCacheInvalidation.ExpectedMVID=35e2cd95-b028-45e3-81fa-8837a703b945&#x000D;&#x000A;</description>
  </entry>
  <entry>
    <record>3304</record>
    <time>2020/06/24 11:55:22.413</time>
    <type>Error</type>
    <source>Microsoft.VisualStudio.ComponentModelHost.VsShellComponentModelHost</source>
    <description>A MEF Component threw an exception at runtime: System.TypeLoadException: Could not load type &apos;Microsoft.CodeQuality.CSharp.Analyzers.ApiDesignGuidelines.CSharpEnumsShouldHavePluralNamesFixer&apos; from assembly &apos;Microsoft.CodeQuality.CSharp.Analyzers, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&apos;.&#x000D;&#x000A;   at System.Reflection.RuntimeModule.GetType(RuntimeModule module, String className, Boolean ignoreCase, Boolean throwOnError, ObjectHandleOnStack type)&#x000D;&#x000A;   at System.Reflection.RuntimeModule.GetType(String className, Boolean throwOnError, Boolean ignoreCase)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.Reflection.TypeRef.get_ResolvedType()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.Reflection.ResolverExtensions.Resolve(MethodRef methodRef)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.Reflection.MethodRef.Resolve()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.&lt;&gt;c__DisplayClass15_0.&lt;GetExportedValueHelper&gt;b__0()</description>
  </entry>
```

**Comment by mavasani** [comment]
Try running “devenv /updateConfiguration”

**Comment by knoxi** [comment]
That helped, and so far I haven't had this exception. I will keep watching this.

**Comment by mavasani** [comment]
Great, thanks. I am going to close out this issue for now. We can reopen it if you see this again.

**Comment by xavave** [comment]
> Try running “devenv /updateConfiguration”


![image](https://user-images.githubusercontent.com/3501675/85630928-d8eb9200-b674-11ea-8a56-1d283e0db67f.png)
Hi,
I still have the (same) issue , I've updated fxcop package with : Install-Package Microsoft.CodeAnalysis.FxCopAnalyzers -version 3.3.0-beta1.20323.3
But, I still cannot use command CTRL+; (which I use all the time for "Quick actions and refactoring") because as soon as I press CTRL+;, type load exception occurs 
(my activitylog files are zipped in attachement : One log file generated before installing  Microsoft.CodeAnalysis.FxCopAnalyzers -version 3.3.0-beta1.20323.3 and one log file generated after installing Microsoft.CodeAnalysis.FxCopAnalyzers -version 3.3.0-beta1.20323.3

[activitylog.zip](https://github.com/dotnet/roslyn-analyzers/files/4828013/activitylog.zip)

Here is my visual studio community 16.6.2 installation information:

Microsoft Visual Studio Community 2019
Version 16.6.2
VisualStudio.16.Release/16.6.2+30204.135
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA682
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.6.948.25768
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2020603+b3ac44798c16fff5b95dbcfe62dea84aa9a1bd72
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.6.948.25768
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.6.948.25768
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.6.948.25768
Azure Functions and Web Jobs Tools

C# Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

GitHub.VisualStudio   2.11.104.25275
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JustDecompilePackage2017 Extension   1.0
JustDecompilePackage2017 Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30212.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.50+g25aae5a24a.R
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.6.17 (9692114)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.20317.1 Commit Hash:3e70368beb9630c811076c051f4c9a59b45d7c10
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Office Developer Tools for Visual Studio   16.0.30007.00
Microsoft Office Developer Tools for Visual Studio

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62006.03190
Microsoft SQL Server Data Tools

StylerPackage Extension   1.0
StylerPackage Visual Stuido Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.20417.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.9.1.0 for F# 4.7   16.6.0-beta.20217.4+1c969cac25e2d38d71872efe6c8226029e42bb59
Microsoft Visual F# Tools 10.9.1.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Unity   4.6.1.0
Visual Studio Tools for Unity

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

WiX Toolset Visual Studio Extension   1.0.0.4
WiX Toolset Visual Studio Extension version 1.0.0.4
Copyright (c) .NET Foundation and contributors. All rights reserved.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   16.6.000.1061 (d16-6@8e68aa8)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.6.0.318 (remotes/origin/d16-6@66afc5421)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.6.40 (1f1466f)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.3.1.4 (d16-6/3a10de9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 165f4b0
    Java.Interop: xamarin/java.interop/d16-6@2cab35c
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.31.1@49232bc
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3


Xamarin.iOS and Xamarin.Mac SDK   13.18.2.1 (29c4ea7)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by mavasani** [comment]
@xavave Can you check if you have "Microsoft CodeAnalysis 2019" VSIX/extension installed? If so, can you please uninstall it?

**Comment by xavave** [comment]
> @xavave Can you check if you have "Microsoft CodeAnalysis 2019" VSIX/extension installed? If so, can you please uninstall it?

When I just disable this extension, CTRL+; works fine again (but it doesn't fix the FXCop issue) 
thanks for your help

**Comment by knoxi** [comment]
@mavasani Do you have an estimation time for the (beta) releases of the fixed analyzers, so we can use them from an official feed?

**Comment by mavasani** [comment]
> Do you have an estimation time for the (beta) releases of the fixed analyzers, so we can use them from an official feed?

@knoxi Which fixed analyzers are you talking about? The issue here was the use of the VSIX extension.

**Comment by knoxi** [comment]
I currently use the package `Microsoft.CodeAnalysis.FxCopAnalyzers (3.3.0-beta1.20323.3)` from your feed as you mentioned in your first response. This solves my issue, but because this package is not published yet I'm waiting for the official beta or release package.

I don't noticed that another workaround is to disable the VSIX extension.
